# SPDX-FileCopyrightText: 2021 Andre 'Staltz' Medeiros
#
# SPDX-License-Identifier: Unlicense

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1

  test:
    name: Test

    strategy:
      matrix:
        node-version: [16.x]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: pnpm install
        uses: jaid/action-npm-install@v1.2.1
        with:
          packageManager: 'pnpm'
      - name: Test
        run: npm test

  publish:
    name: Publish fixtures
    needs: [test]
    if: ${{ startsWith(github.event.head_commit.message, 'release') }}

    strategy:
      matrix:
        node-version: [12.x]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: pnpm install
        uses: jaid/action-npm-install@v1.2.1
        with:
          packageManager: 'pnpm'

      - name: Compile
        run: npm run compile

      - name: Detect version
        run: echo "FULL_VERSION=$(node .github/get-pkg-version.js)" >> $GITHUB_ENV

      - name: Detect major version
        run: echo "MAJOR_VERSION=$(node .github/get-pkg-major-version.js)" >> $GITHUB_ENV

      - name: Build 'dinghy' fixture
        run: |
          node lib/bin.js --seed=dinghy --messages=10000 --authors=500 --allkeys --followGraph --outputDir=dinghy

      - name: Build 'sloop' fixture
        run: |
          node lib/bin.js --seed=sloop --messages=100000 --authors=2000 --allkeys --followGraph --outputDir=sloop

      - name: Build 'catamaran' fixture
        run: |
          node lib/bin.js --seed=catamaran --messages=1000000 --authors=8000 --allkeys --followGraph --outputDir=catamaran

      - name: Compress 'dinghy'
        run: cd ./dinghy && tar -zcvf ../v${{ env.MAJOR_VERSION }}-dinghy-m10000-a500.tar.gz . && cd ..

      - name: Compress 'sloop'
        run: cd ./sloop && tar -zcvf ../v${{ env.MAJOR_VERSION }}-sloop-m100000-a2000.tar.gz . && cd ..

      - name: Compress 'catamaran'
        run: cd ./catamaran && tar -zcvf ../v${{ env.MAJOR_VERSION }}-catamaran-m1000000-a8000.tar.gz . && cd ..

      - name: Upload to GitHub releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'v${{ env.MAJOR_VERSION }}-dinghy-m10000-a500.tar.gz,v${{ env.MAJOR_VERSION }}-sloop-m100000-a2000.tar.gz,v${{ env.MAJOR_VERSION }}-catamaran-m1000000-a8000.tar.gz'
          allowUpdates: true
          omitBodyDuringUpdate: true
          tag: ${{ env.FULL_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
